#!/bin/bash
# Update from GIT and Joukahainen without overriding local changes
make clean
git checkout vocabulary/joukahainen.xml
git stash
git pull -r
git stash pop
make update-vocabulary
make voikko

