.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH VOIKKOSPELL 1 "2010-05-11"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
voikkospell \- test program for Voikko spell checker
.SH SYNOPSIS
.B voikkospell
.RI [ options ]
.SH DESCRIPTION
.B voikkospell
is a test program for spell checking functionality in libvoikko,
library of Finnish language tools.
It reads words from stdin (one word on a line) and print them to stdout, adding
"C: " in front of correct words and "W: " in front of incorrect words.

Common options of different Voikko test programs are listed in COMMON OPTIONS.
.SH OPTIONS
.TP
.B \-m
Prints morphological analysis info (A:) for recognized words.
.TP
.B \-t
Prints only "C" or "W" instead of typical full output.
.TP
.B \-tt
Prints only misspelled words.
.TP
.B \-s
Prints suggestions (S:) for incorrectly spelled words.
.TP
.BI \-c n
Set cache size parameter to
.IR n .
\-1 disables the cache and 0 is the default.
For checking large amounts of unsorted text you may want to set
.I n
to 5 to get better performance.
.TP
.BI \-j " n"
Use
.I n
threads for spell checking. When more than one thread is used checking is
performed using large internal buffers which is why this mode should only
be used for batch processing.
.TP
.BI \-x c
Like
.B voikkospell -s
but output is printed on one line separated by character
.IR c 
without "C", "W" or "S" in front of the words.
If
.IR c
is not defined words are separated by space and suggestions that have
spaces in them are not printed.
.TP
.B \-l
Prints a list of available dictionary variants and exits. The first variant
is the default to be used when no specific variant has been requested.
.TP
.BI ignore_nonwords= n
.TP
.BI accept_first_uppercase= n
.TP
.BI accept_extra_hyphens= n
.TP
.BI accept_missing_hyphens= n
.TP
.BI ocr_suggestions= n
.br
Set the value of the specified boolean option.
.I n
can be either 0 (false) or 1 (true).
.SH COMMON OPTIONS
.TP
.BI \-p " directory"
(voikkospell, voikkohyphenate, voikkogc)
Look from
.I directory
before the standard locations when searching for dictionary files.
.TP
.BI \-d " variant"
(voikkospell, voikkohyphenate, voikkogc)
Use dictionary variant
.I variant
instead of the default dictionary variant. The variant must be represented as a BCP 47 language tag.
.TP
.BI ignore_dot= n
(voikkospell, voikkohyphenate)
.TP
.BI ignore_numbers= n
(voikkospell, voikkohyphenate)
.br
Set the value of the specified boolean option.
.I n
can be either 0 (false) or 1 (true).
.TP
.B \-h, --help
Print a help message and exit.
.SH AUTHOR
voikkospell and this manual page were written by \%Harri \%Pitk\[:a]nen \%(hatapitk@iki.fi).
